### ISSUE TITLE
ERROR: cannot send statistics to Home Assistant: error unknown_error: Invalid statistic_id

### ISSUE THREAD

**Issue by oriold** [Lorentz83/esb2ha#1]
I get the following error when running this.

Do you know how you can fix this? The output from ESB seems correct and the sensor was created as documented.

**Comment by oriold** [comment]
Actually I get this error with the provided sensor config:

`Invalid config for [template]: required key not provided @ data['trigger'][0]['platform']`

**Comment by Lorentz83** [comment]
Did you configure home assistant sensor as described in https://github.com/Lorentz83/esb2ha/blob/main/documentation/index.md#configuring-home-assistant ?

If you do the quick and dirty test using a dockerized home assistant  (https://github.com/Lorentz83/esb2ha/blob/main/documentation/index.md#i-just-wan-to-give-it-a-quick-try) does it work?

**Comment by oriold** [comment]
The sensor is exactly the same.

I have run the test and the test works. So I am going to investigate the issue. Not sure what it is.
