### ISSUE TITLE
ESB changed the download patterns of historic data, script is broken

### ISSUE THREAD

**Issue by oriold** [Lorentz83/esb2ha#3]
I can see the script failing claiming that there is nothing to download.

According to this other project [esb-smart-meter-automation](https://github.com/badger707/esb-smart-meter-reading-automation), the pattern has changed. You can see that now there is even a split version between day/peak/night consumption.

**Comment by Lorentz83** [comment]
Thank you for the notification. 

I realized I didn't use this data as much as expected. But I'd like to keep this project alive. I'll see if I can fix it.

**Comment by Lorentz83** [comment]
It should be fixed now.
